config/routes.rb
Rails.application.routes.draw do
  get '/user/:id' => 'users#show', as: :user_profile
  devise_scope :user do
    # Redirects users back to homepage when deleting account
    get "users", to: "site#home"
  end
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks",
  }
  root "site#home"
  get '/about' => "site#about"
  get '/privacy' => "site#privacy"
  get '/contact' => "site#contact"
  get "/legal" => "site#legal"

  get "/activities/user/:uid" => 'activities#list_user_activities', as: :user_activities
  resources :activities
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  # GET /activities/:id or /activities.json
  def index
    @activities = Activity.all
  end

  def list_user_activities
    @activities = 
      Activity
      .where(user_id: params[:uid])
      .order("date DESC")
      .order("time DESC")
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    # @activity = Activity.new
    @activity = current_user.activities.build
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    # @activity = Activity.new(activity_params)
    @activity = current_user.activities.build(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to user_activities_path(current_user.id), notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    def correct_user
      @activity = current_user.activities.find_by(id: params[:id])
      redirect_to user_activities_path(current_user.id), alert: "Not authorized to edit or delete this activity" if @activity.nil?
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:name, :date, :time, :duration, :user_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
    def getUsername(user_id)
        user = User.find(user_id)
        user.first_name + " " + user.last_name
    end

    def getUserFirstName(user_id)
        User.find(user_id).first_name
    end

    def activity_img(activity_name)
        case activity_name
        when "Running"
            'running'
        when "Cycling"
            'cycling'
        when "Swimming"
            'swimming'
        when "Walking"
            'hiking'
        when "Skiing"
            'skiing'
        when "Weightlifting"
            'lifting'
        when "Yoga"
            'yoga'
        when "Rowing"
            'rowing'
        when "Skateboarding"
            'skateboarding'
        when "Climbing"
            'climbing'
        when 'Tennis'
            'tennis'
        when 'Soccer'
            'soccer'
        when 'Basket'
            'basket'
        else
            nil
        end 
    end
end

app/views/activities/_activity.html.erb
<h1 class="text-orange mb-5"><%= activity.name %></h1>
<p>By <%= link_to "#{getUsername(activity.user_id)}", user_profile_path(activity.user_id), class: "text-decoration-none text-orange fw-bold" %>, on <%= activity.date %> at <%= activity.time.strftime('%H:%M') %></p>
<p>Duration: <%= activity.duration.strftime('%H:%M:%S') %></p>

app/views/activities/_activity_card.html.erb
<div class="col">
  <div id="<%= dom_id activity %>" class="card my-2 mx-auto" style="width: 16rem; height: 22rem" role="button">
    <div class="card-img <%= activity_img(activity.name) %>"></div>
    <div class="card-body">
      <h5 class="card-title"><%= activity.name %></h5>
      <p class="card-text m-3"><%= activity.date %> at <%= activity.time.strftime('%H:%M') %></p>
      <p class="card-text mb-2">Duration: <%= activity.duration.strftime('%H:%M:%S') %></p>
      <%= link_to "Show this activity", activity, class: "btn btn-orange mt-2 stretched-link" %>
    </div>
  </div>
</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :user_id, id: :activity_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="mb-3">
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.select :name, [
      "Running", 
      "Swimming", 
      "Walking", 
      "Cycling", 
      "Skiing", 
      "Weightlifting", 
      "Rowing", 
      "Skateboarding",
      "Yoga",
      "Climbing",
      "Tennis",
      "Soccer",
      "Basket"
    ], {}, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.label :date, style: "display: block", class: "form-label" %>
    <%= form.date_field :date, class: "form-control" %>
  </div>

    <div class="mb-3">
      <%= form.label :time, style: "display: block", class: "form-label" %>
      <%= form.time_field :time, class: "form-control" %>
    </div>

  <div class="mb-3">
    <%= form.label :duration, style: "display: block", class: "form-label" %>
    <%= form.time_field :duration, class: "form-control" %>
  </div>

  <div class="text-center mb-3">
    <% if current_page?(controller: 'activities', action: 'new') %>
      <%= form.submit "Create", class: "btn btn-orange" %>
    <% elsif current_page?(controller: 'activities', action: 'edit') %>
      <%= form.submit "Update", class: "btn btn-orange" %>
    <% end %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<div class= "mx-auto w-50 my-3">
  <h1>Editing activity</h1>

  <%= render "form", activity: @activity %>

  <div class="d-lg-block d-flex flex-column text-center">
    <%= link_to "Show this activity", @activity, class: "text-green-dark" %> <span class="d-none d-lg-inline">|</span>
    <%= link_to "Back to activities", user_activities_path(current_user.id), class: "text-green-dark" %>
  </div>
</div>

app/views/activities/index.html.erb
<div class="text-center">
  <h1>Your activities</h1>

  <div id="activities" class="container p-3 d-flex flex-wrap justify-content-center">
    <% @activities.each do |activity| %>
        <%= render partial: "activity_card", locals: {activity: activity} %>
    <% end %>
  </div>
  
  <% if params[:id].to_i == current_user.id %>
    <%= link_to "New activity", new_activity_path, class: "btn btn-green" %>
  <% end %>
</div>

app/views/activities/list_user_activities.html.erb
<div class="text-center my-3">
  <h1>Your activities</h1>

  <% if params[:uid].to_i == current_user.id %>
    <%= link_to "New activity", new_activity_path, class: "btn btn-green mt-2" %>
  <% end %>

  <div id="activities" class="container p-3 mx-auto row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4">
    <% @activities.each do |activity| %>
        <%= render partial: "activity_card", locals: {activity: activity} %>
    <% end %>
  </div>
</div>

app/views/activities/new.html.erb
<div class= "mx-auto w-50 my-3">
  <h1>New activity</h1>

  <%= render "form", activity: @activity %>

  <div class="text-center">
    <%= link_to "Back to your activities", user_activities_path(current_user.id), class: "text-green-dark" %>
  </div>
</div>

app/views/activities/show.html.erb
<div id="activity" class="position-absolute top-45 start-50 translate-middle w-50 text-center border border-orange rounded p-3 bg-light">
  <%= render @activity %>

  <div>
    <% if @activity.user_id == current_user.id %>
      <%= link_to "Edit this activity", edit_activity_path(@activity), class: "text-green-dark" %> | <%= link_to "Back to your activities", user_activities_path(@activity.user_id), class: "text-green-dark" %>
    <% else %>
      <%= link_to "Back to #{getUserFirstName(@activity.user_id)}'s activities", user_activities_path(@activity.user_id), class: "text-green-dark" %>
    <% end %>
    

    <%= button_to "Destroy this activity", @activity, method: :delete, class: "btn btn-danger mt-3", data: {confirm: "Are you sure?"} if @activity.user_id == current_user.id %>
  </div>
</div>