config/routes.rb
Rails.application.routes.draw do
  get '/user/:id' => 'users#show', as: :user_profile
  devise_scope :user do
    # Redirects users back to homepage when deleting account
    get "users", to: "site#home"
  end
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks",
  }
  root "site#home"
  get '/about' => "site#about"
  get '/privacy' => "site#privacy"
  get '/contact' => "site#contact"
  get "/legal" => "site#legal"

  get "/activities/user/:uid" => 'activities#list_user_activities', as: :user_activities
  resources :activities
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_alerts.html.erb
 <% if notice %>
    <div class="alert alert-success alert-dismissible fade show w-50 text-center position-fixed bottom-0 mb-0 start-50 translate-middle-x z-1" role="alert">
        <p><%= notice %><p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% elsif alert %>
    <div class="alert alert-danger alert-dismissible fade show w-50 text-center position-fixed bottom-0 mb-0 start-50 translate-middle-x z-1" role="alert">
        <p><%= alert %><p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<ul class="nav justify-content-center border-bottom py-3 mb-3">
    <li class="nav-item">
        <%= link_to 'Home', root_path, class: "nav-link px-2 text-muted" %>
    </li>
    <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link px-2 text-muted" %>
    </li>
    <li class="nav-item">
        <%= link_to 'Legal', legal_path, class: "nav-link px-2 text-muted" %>
    </li>
    <li class="nav-item">
        <%= link_to 'Privacy', privacy_path, class: "nav-link px-2 text-muted" %>
    </li>
    <li class="nav-item">
        <%= link_to 'Contact us', contact_path, class: "nav-link px-2 text-muted" %>
    </li>
</ul>
<div class="d-flex justify-content-between mx-5">
    <p class="text-muted mb-0 pb-3">&copy; <%= DateTime.current.year %> Move & Groove, inc.</p>
    <ul class="list-unstyled d-flex">
        <li class="ms-3">
            <a href="#" class="link-dark">
                <svg class="bi" width="24" height="24">
                    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
                </svg>
            </a>
        </li>
        <li class="ms-3">
            <a href="#" class="link-dark">
                <svg class="bi" width="24" height="24">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
                </svg>
            </a>
        </li>
        <li class="ms-3">
            <a href="#" class="link-dark">
                <svg class="bi" width="24" height="24">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
                </svg>
            </a>
        </li>
    </ul>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-lime z-1">
  <div class="container-fluid">
    <%= link_to 'Move & Groove', root_path, class: "navbar-brand ms-3 text-orange fw-bold" %>
    <button class="navbar-toggler me-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-3 mb-2 mb-lg-0 justify-content-end flex-grow-1">
        <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <%= link_to "Hi #{current_user.first_name}!", '#', class: "nav-link dropdown-toggle #{set_active_class(["/user/#{current_user.id}", "/activities/user/#{current_user.id}", "/activities/new"])}", id: 'navbarDropdown', role: "button", data: {"bs-toggle": "dropdown"}, aria: {expanded: false} %>

              <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "Profile", user_profile_path(current_user.id), class: "dropdown-item text-green-dark #{set_active_class("/user/#{current_user.id}")}" %>
                </li>
                <li>
                  <%= link_to 'Your activities', user_activities_path(current_user.id), class: "dropdown-item text-green-dark #{set_active_class("/activities/user/#{current_user.id}")}" %>
                </li>                
                <li>
                  <%= link_to 'Add activity', new_activity_path, class: "dropdown-item text-green-dark #{set_active_class('/activities/new')}" %>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li>
                  <%= link_to 'Sign out', destroy_user_session_path, class: "dropdown-item text-orange", data: {"turbo-method": :delete} %>
                </li>
              </ul>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, class: "nav-link #{set_active_class('/users/sign_in')}" %>
            </li>
            <li class="nav-item py-2 d-none d-lg-block">
                |
            </li>
            <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: "nav-link #{set_active_class('/users/sign_up')}" %>
            </li>
        <% end %>
        <li class="nav-item">
            <%= link_to 'About', about_path, class: "nav-link #{set_active_class('/about')}" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Move & Groove</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render "layouts/nav" %>
    </header>

    <main>
     <%= render "layouts/alerts" %>

      <%= yield %>
    </main>

    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>